import * as fs from 'fs';
import * as path from 'path';
import type { ChikaGroup } from '../src/lib/schema';

export const CHIKA_GROUPS_EXPANDED: ChikaGroup[] = [
  // ==========================================
  // [1] 도쿄 - 하라주쿠: FRUITS ZIPPER
  // ==========================================
  {
    id: 'fruits-zipper',
    name: { ja: 'FRUITS ZIPPER', ko: '후르츠 지퍼 (FRUITS ZIPPER)', en: 'FRUITS ZIPPER' },
    shortName: { ja: 'ふるっぱー', ko: '후룹파', en: 'FZ' },
    agency: 'ASOBISYSTEM (KAWAII LAB.)',
    region: 'tokyo',
    district: 'harajuku',
    color: '#FF6EA7',
    accentColor: '#FFE5EC',
    debutYear: 2022,
    imageUrl: '/images/groups/fruits-zipper.svg',
    description: {
      ja: '「原宿から世界へ」をコンセプトに、「わたしの一番かわいいところ」がTikTok 9億再生を突破したKAWAII LAB.の第1弾フラッグシップグループ。',
      ko: '「하라주쿠에서 세계로」를 콘셉트로 「내가 가장 귀여운 곳」이 틱톡 9억 뷰를 돌파한 카와이 랩의 제1탄 대표 걸그룹.',
      en: 'The flagship breakthrough idol group of KAWAII LAB. transmitting Harajuku kawaii culture worldwide.',
    },
    officialSite: 'https://fruitszipper.asobisystem.com/',
    ticketUrl: 'https://l-tike.com/fruitszipper/',
    chekiUrl: 'https://kawaiilab.stores.jp/',
    scheduleUrl: 'https://fruitszipper.asobisystem.com/schedule/',
    x: 'https://x.com/fruits_zipper',
    instagram: 'https://www.instagram.com/fruits_zipper/',
    tiktok: 'https://www.tiktok.com/@fruits_zipper',
    youtube: 'https://www.youtube.com/@fruitszipper3799',
    subUnits: [],
    members: [
      {
        id: 'fz-matsumoto-karen',
        groupId: 'fruits-zipper',
        subUnitId: '',
        name: { ja: { kanji: '松本かれん', kana: 'まつもと かれん' }, ko: { hangul: '마츠모토 카렌' }, en: { romaji: 'Karen Matsumoto' } },
        memberColor: '#FFA7C4',
        memberColorName: { ja: 'ベビーピンク', ko: '베이비 핑크', en: 'Baby Pink' },
        imageUrl: '/images/members/fz-matsumoto-karen.svg',
        birthDate: '2002-03-28',
        birthplace: { ja: '千葉県', ko: '지바현', en: 'Chiba' },
        nickname: { ja: 'かれんたん', ko: '카렌탄', en: 'Karentan' },
        links: [
          { type: 'x', url: 'https://x.com/karen_fz0328', label: { ja: 'X (Twitter)', ko: '공식 X (트위터)', en: 'Official X' }, verified: true, isPrimary: true },
          { type: 'instagram', url: 'https://www.instagram.com/karen_matsumoto_/', label: { ja: 'Instagram', ko: '인스타그램', en: 'Instagram' }, verified: true, isPrimary: true },
        ],
      },
      {
        id: 'fz-sakurai-yui',
        groupId: 'fruits-zipper',
        subUnitId: '',
        name: { ja: { kanji: '櫻井優衣', kana: 'さくらい ゆい' }, ko: { hangul: '사쿠라이 유이' }, en: { romaji: 'Yui Sakurai' } },
        memberColor: '#72D792',
        memberColorName: { ja: 'ミントグリーン', ko: '민트 그린', en: 'Mint Green' },
        imageUrl: '/images/members/fz-sakurai-yui.svg',
        birthDate: '2000-02-21',
        birthplace: { ja: '東京都', ko: '도쿄도', en: 'Tokyo' },
        nickname: { ja: 'ゆいちゃん', ko: '유이짱', en: 'Yui-chan' },
        links: [
          { type: 'x', url: 'https://x.com/yui_fz0221', label: { ja: 'X (Twitter)', ko: '공식 X (트위터)', en: 'Official X' }, verified: true, isPrimary: true },
          { type: 'instagram', url: 'https://www.instagram.com/yui.sakurai_7/', label: { ja: 'Instagram', ko: '인스타그램', en: 'Instagram' }, verified: true, isPrimary: true },
        ],
      },
      {
        id: 'fz-chinzei-suzuka',
        groupId: 'fruits-zipper',
        subUnitId: '',
        name: { ja: { kanji: '鎮西寿々歌', kana: 'ちんぜい すずか' }, ko: { hangul: '친제이 스즈카' }, en: { romaji: 'Suzuka Chinzei' } },
        memberColor: '#FF9E40',
        memberColorName: { ja: 'オレンジ', ko: '오렌지', en: 'Orange' },
        imageUrl: '/images/members/fz-chinzei-suzuka.svg',
        birthDate: '1998-11-24',
        birthplace: { ja: '兵庫県', ko: '효고현', en: 'Hyogo' },
        nickname: { ja: 'おすず', ko: '오스즈', en: 'Osuzu' },
        links: [
          { type: 'x', url: 'https://x.com/suzuka_fz1124', label: { ja: 'X (Twitter)', ko: '공식 X (트위터)', en: 'Official X' }, verified: true, isPrimary: true },
          { type: 'instagram', url: 'https://www.instagram.com/tarasuzuka24/', label: { ja: 'Instagram', ko: '인스타그램', en: 'Instagram' }, verified: true, isPrimary: true },
        ],
      },
    ],
  },

  // ==========================================
  // [2] 도쿄 - 하라주쿠: CANDY TUNE
  // ==========================================
  {
    id: 'candy-tune',
    name: { ja: 'CANDY TUNE', ko: '캔디 튠 (CANDY TUNE)', en: 'CANDY TUNE' },
    shortName: { ja: 'きゃんちゅー', ko: '캔츄', en: 'CT' },
    agency: 'ASOBISYSTEM (KAWAII LAB.)',
    region: 'tokyo',
    district: 'harajuku',
    color: '#FF69B4',
    accentColor: '#FFE4E6',
    debutYear: 2023,
    imageUrl: '/images/groups/candy-tune.svg',
    description: {
      ja: '「フレーフレー私！」などポップでキュートな王道アイドルソングを届けるKAWAII LAB.第2弾アイドルグループ。',
      ko: '「힘내라 나!」 등 톡톡 튀는 캔디 같은 사운드와 카와이 매력으로 주목받는 카와이 랩 제2탄 걸그룹.',
      en: 'The second idol group from KAWAII LAB. radiating colorful and energetic pop tunes.',
    },
    officialSite: 'https://candy-tune.asobisystem.com/',
    ticketUrl: 'https://l-tike.com/candytune/',
    chekiUrl: 'https://kawaiilab.stores.jp/',
    scheduleUrl: 'https://candy-tune.asobisystem.com/schedule/',
    x: 'https://x.com/CANDY_TUNE_',
    instagram: 'https://www.instagram.com/candy__tune/',
    tiktok: 'https://www.tiktok.com/@candy_tune',
    youtube: 'https://www.youtube.com/@CANDYTUNE',
    subUnits: [],
    members: [
      {
        id: 'ct-murakawa-bibian',
        groupId: 'candy-tune',
        subUnitId: '',
        name: { ja: { kanji: '村川緋杏', kana: 'むらかわ びびあん' }, ko: { hangul: '무라카와 비비안' }, en: { romaji: 'Bibian Murakawa' } },
        memberColor: '#FF69B4',
        memberColorName: { ja: 'ピンク', ko: '핑크', en: 'Pink' },
        imageUrl: '/images/members/ct-murakawa-bibian.svg',
        birthDate: '1999-12-03',
        birthplace: { ja: '福岡県', ko: '후쿠오카현', en: 'Fukuoka' },
        nickname: { ja: 'びびあん', ko: '비비안', en: 'Bibian' },
        links: [
          { type: 'x', url: 'https://x.com/bibian_ct1203', label: { ja: 'X (Twitter)', ko: '공식 X (트위터)', en: 'Official X' }, verified: true, isPrimary: true },
        ],
      },
      {
        id: 'ct-kano-nanako',
        groupId: 'candy-tune',
        subUnitId: '',
        name: { ja: { kanji: '小川奈々子', kana: 'おがわ ななこ' }, ko: { hangul: '오가와 나나코' }, en: { romaji: 'Nanako Ogawa' } },
        memberColor: '#4169E1',
        memberColorName: { ja: 'ブルー', ko: '블루', en: 'Blue' },
        imageUrl: '/images/members/ct-kano-nanako.svg',
        birthDate: '1999-10-01',
        birthplace: { ja: '北海道', ko: '홋카이도', en: 'Hokkaido' },
        nickname: { ja: 'ななこ', ko: '나나코', en: 'Nanako' },
        links: [
          { type: 'x', url: 'https://x.com/nachico_ct1001', label: { ja: 'X (Twitter)', ko: '공식 X (트위터)', en: 'Official X' }, verified: true, isPrimary: true },
        ],
      },
    ],
  },

  // ==========================================
  // [3] 도쿄 - 하라주쿠: CUTIE STREET
  // ==========================================
  {
    id: 'cutie-street',
    name: { ja: 'CUTIE STREET', ko: '큐티 스트리트 (CUTIE STREET)', en: 'CUTIE STREET' },
    shortName: { ja: 'きゅーすと', ko: '큐스토', en: 'CS' },
    agency: 'ASOBISYSTEM (KAWAII LAB.)',
    region: 'tokyo',
    district: 'harajuku',
    color: '#FF0080',
    accentColor: '#FFE5F1',
    debutYear: 2024,
    imageUrl: '/images/groups/cutie-street.svg',
    description: {
      ja: '「KAWAII MAKER」をコンセプトに原宿ストリートから最新トレンドを発信するKAWAII LAB.の第4弾グループ。',
      ko: '「KAWAII MAKER」를 테마로 하라주쿠 스트리트 감성과 최신 트렌드를 전파하는 카와이 랩 제4탄 걸그룹.',
      en: 'The 4th sensation group of KAWAII LAB. setting fresh Harajuku street trends.',
    },
    officialSite: 'https://cutiestreet.asobisystem.com/',
    ticketUrl: 'https://l-tike.com/cutiestreet/',
    chekiUrl: 'https://kawaiilab.stores.jp/',
    scheduleUrl: 'https://cutiestreet.asobisystem.com/schedule/',
    x: 'https://x.com/CUTIE_STREET_',
    instagram: 'https://www.instagram.com/cutie_street_/',
    tiktok: 'https://www.tiktok.com/@cutie_street',
    youtube: 'https://www.youtube.com/@CUTIESTREET',
    subUnits: [],
    members: [
      {
        id: 'cs-sakuraba-haruka',
        groupId: 'cutie-street',
        subUnitId: '',
        name: { ja: { kanji: '桜庭遥花', kana: 'さくらば はるか' }, ko: { hangul: '사쿠라바 하루카' }, en: { romaji: 'Haruka Sakuraba' } },
        memberColor: '#FF69B4',
        memberColorName: { ja: 'ぴんく', ko: '핑크', en: 'Pink' },
        imageUrl: '/images/members/cs-sakuraba-haruka.svg',
        birthDate: '2006-01-29',
        birthplace: { ja: '北海道', ko: '홋카이도', en: 'Hokkaido' },
        nickname: { ja: 'ぱるたん', ko: '파루탄', en: 'Parutan' },
        links: [
          { type: 'x', url: 'https://x.com/haruka_cs0129', label: { ja: 'X (Twitter)', ko: '공식 X', en: 'Official X' }, verified: true, isPrimary: true },
        ],
      },
    ],
  },

  // ==========================================
  // [4] 도쿄 - 하라주쿠: SWEET STEADY
  // ==========================================
  {
    id: 'sweet-steady',
    name: { ja: 'SWEET STEADY', ko: '스위트 스테디 (SWEET STEADY)', en: 'SWEET STEADY' },
    shortName: { ja: 'すいすて', ko: '스이스테', en: 'Suisute' },
    agency: 'ASOBISYSTEM (KAWAII LAB.)',
    region: 'tokyo',
    district: 'harajuku',
    color: '#A78BFA',
    accentColor: '#F5F3FF',
    debutYear: 2024,
    imageUrl: '/images/groups/sweet-steady.svg',
    description: {
      ja: '「かわいい」の王道を受け継ぐKAWAII LAB.の第3弾清純派アイドルグループ。',
      ko: '청순함과 달콤한 카와이 매력을 선사하는 카와이 랩 제3탄 청순파 걸그룹.',
      en: 'The 3rd group of KAWAII LAB. delivering pure, sweet idol aesthetics.',
    },
    officialSite: 'https://sweetsteady.asobisystem.com/',
    ticketUrl: 'https://l-tike.com/sweetsteady/',
    chekiUrl: 'https://kawaiilab.stores.jp/',
    scheduleUrl: 'https://sweetsteady.asobisystem.com/schedule/',
    x: 'https://x.com/SWEET_STEADY_',
    instagram: 'https://www.instagram.com/sweet_steady_/',
    tiktok: 'https://www.tiktok.com/@sweet_steady',
    youtube: 'https://www.youtube.com/@SWEETSTEADY',
    subUnits: [],
    members: [
      {
        id: 'ss-okuda-ayuka',
        groupId: 'sweet-steady',
        subUnitId: '',
        name: { ja: { kanji: '奥田彩友', kana: 'おくだ あゆか' }, ko: { hangul: '오쿠다 아유카' }, en: { romaji: 'Ayuka Okuda' } },
        memberColor: '#4169E1',
        memberColorName: { ja: 'ブルー', ko: '블루', en: 'Blue' },
        imageUrl: '/images/members/ss-okuda-ayuka.svg',
        birthDate: '2001-01-07',
        birthplace: { ja: '福井県', ko: '후쿠이현', en: 'Fukui' },
        nickname: { ja: 'あゆか', ko: '아유카', en: 'Ayuka' },
        links: [
          { type: 'x', url: 'https://x.com/ayuka_ss0107', label: { ja: 'X (Twitter)', ko: '공식 X', en: 'Official X' }, verified: true, isPrimary: true },
        ],
      },
    ],
  },

  // ==========================================
  // [5] 도쿄 - 신주쿠: iLiFE!
  // ==========================================
  {
    id: 'ilife',
    name: { ja: 'iLiFE!', ko: '아이라이프 (iLiFE!)', en: 'iLiFE!' },
    shortName: { ja: 'アイライフ', ko: '아이라이프', en: 'iLiFE!' },
    agency: 'HEROINES (imaginate)',
    region: 'tokyo',
    district: 'shinjuku',
    color: '#FF2E7E',
    accentColor: '#FFD6E5',
    debutYear: 2020,
    imageUrl: '/images/groups/ilife.svg',
    description: {
      ja: '「私（i）と貴方（you）で創るアイドル（iLiFE!）」をコンセプトに、爆発的なライブ動員を誇るHEROINESのフラッグシップグループ。',
      ko: '「나(i)와 당신(you)이 함께 만드는 아이돌」을 콘셉트로 폭발적인 라이브 동원력을 자랑하는 HEROINES 대표 걸그룹.',
      en: 'The top flagship group of HEROINES creating explosive festival energy together with fans.',
    },
    officialSite: 'https://heroines.jp/artist/ilife',
    ticketUrl: 'https://ticketdive.com/artist/ilife',
    chekiUrl: 'https://heroines.stores.jp/',
    scheduleUrl: 'https://timetreeapp.com/public_calendars/ilife_official',
    x: 'https://x.com/iLiFE_official',
    instagram: 'https://www.instagram.com/ilife.heroines/',
    tiktok: 'https://www.tiktok.com/@ilife.heroines',
    youtube: 'https://www.youtube.com/@iLiFE_official',
    subUnits: [],
    members: [
      {
        id: 'ilife-shinzome-riri',
        groupId: 'ilife',
        subUnitId: '',
        name: { ja: { kanji: '心花りり', kana: 'しんぞめ りり' }, ko: { hangul: '신조메 리리' }, en: { romaji: 'Riri Shinzome' } },
        memberColor: '#E60033',
        memberColorName: { ja: '赤色', ko: '레드', en: 'Red' },
        imageUrl: '/images/members/ilife-shinzome-riri.svg',
        birthDate: '2000-05-19',
        birthplace: { ja: '神奈川県', ko: '가나가와현', en: 'Kanagawa' },
        nickname: { ja: 'りりちゃん', ko: '리리짱', en: 'Riri-chan' },
        links: [
          { type: 'x', url: 'https://x.com/iLiFE_riri', label: { ja: 'X (Twitter)', ko: '공식 X (트위터)', en: 'Official X' }, verified: true, isPrimary: true },
          { type: 'instagram', url: 'https://www.instagram.com/riri_shinzome/', label: { ja: 'Instagram', ko: '인스타그램', en: 'Instagram' }, verified: true, isPrimary: true },
        ],
      },
      {
        id: 'ilife-aisu',
        groupId: 'ilife',
        subUnitId: '',
        name: { ja: { kanji: 'あいす', kana: 'あいす' }, ko: { hangul: '아이스' }, en: { romaji: 'Aisu' } },
        memberColor: '#B0E0E6',
        memberColorName: { ja: '白色・水色', ko: '화이트/라이트블루', en: 'White Light Blue' },
        imageUrl: '/images/members/ilife-aisu.svg',
        birthDate: '2006-01-24',
        birthplace: { ja: '東京都', ko: '도쿄도', en: 'Tokyo' },
        nickname: { ja: 'あいす', ko: '아이스', en: 'Aisu' },
        links: [
          { type: 'x', url: 'https://x.com/iLiFE_aisu', label: { ja: 'X (Twitter)', ko: '공식 X (트위터)', en: 'Official X' }, verified: true, isPrimary: true },
          { type: 'instagram', url: 'https://www.instagram.com/aisu_ilife/', label: { ja: 'Instagram', ko: '인스타그램', en: 'Instagram' }, verified: true, isPrimary: true },
        ],
      },
    ],
  },

  // ==========================================
  // [6] 도쿄 - 신주쿠: 夜光性アミューズ
  // ==========================================
  {
    id: 'yoruamu',
    name: { ja: '夜光性アミューズ', ko: '야광성 어뮤즈 (Yakousei Amuse)', en: 'Yakousei Amuse' },
    shortName: { ja: 'よるあみ', ko: '요루아미', en: 'YoruAmu' },
    agency: 'HEROINES (imaginate)',
    region: 'tokyo',
    district: 'shinjuku',
    color: '#8B5CF6',
    accentColor: '#EDE9FE',
    debutYear: 2021,
    imageUrl: '/images/groups/yoruamu.svg',
    description: {
      ja: '「夜に輝くアミューズメントパーク」をテーマにしたHEROINES所属のエレクトロニック・ポップアイドル。',
      ko: '「밤에 빛나는 놀이공원」을 테마로 감각적인 일렉트로닉 팝을 선보이는 HEROINES 대표 걸그룹.',
      en: 'The vibrant electronic pop idol sensation lighting up Shinjuku and Tokyo nights.',
    },
    officialSite: 'https://heroines.jp/artist/yoruamu',
    ticketUrl: 'https://ticketdive.com/artist/yoruamu',
    chekiUrl: 'https://heroines.stores.jp/',
    scheduleUrl: 'https://timetreeapp.com/public_calendars/yoruamu_official',
    x: 'https://x.com/Yorusei_Amuse',
    instagram: 'https://www.instagram.com/yoruami_official/',
    tiktok: 'https://www.tiktok.com/@yorusei_amuse',
    youtube: 'https://www.youtube.com/@Yorusei_Amuse',
    subUnits: [],
    members: [
      {
        id: 'ya-mitsuki-hina',
        groupId: 'yoruamu',
        subUnitId: '',
        name: { ja: { kanji: 'みつきひな', kana: 'みつき ひな' }, ko: { hangul: '미츠키 히나' }, en: { romaji: 'Hina Mitsuki' } },
        memberColor: '#38BDF8',
        memberColorName: { ja: '水色', ko: '라이트블루', en: 'Light Blue' },
        imageUrl: '/images/members/ya-mitsuki-hina.svg',
        birthDate: '2000-08-08',
        birthplace: { ja: '東京都', ko: '도쿄도', en: 'Tokyo' },
        nickname: { ja: 'ひなちゃん', ko: '히나짱', en: 'Hina-chan' },
        links: [
          { type: 'x', url: 'https://x.com/hina_yoruamu', label: { ja: 'X (Twitter)', ko: '공식 X', en: 'Official X' }, verified: true, isPrimary: true },
        ],
      },
    ],
  },

  // ==========================================
  // [7] 도쿄 - 신주쿠: のんふぃく！ (NonFiction)
  // ==========================================
  {
    id: 'nonfic',
    name: { ja: 'のんふぃく！', ko: '논픽션 (NonFiction)', en: 'NonFiction' },
    shortName: { ja: 'のんふぃく', ko: '논픽', en: 'NonFic' },
    agency: 'HEROINES (imaginate)',
    region: 'tokyo',
    district: 'shinjuku',
    color: '#EC4899',
    accentColor: '#FDF2F8',
    debutYear: 2021,
    imageUrl: '/images/groups/nonfic.svg',
    description: {
      ja: '「ノンフィクションな現実を可愛く生きる」を掲げ、疾走感あるサウンドで人気を集めるHEROINESグループ。',
      ko: '「논픽션 같은 현실을 귀엽고 당당하게 살아간다」를 모토로 질주감 넘치는 사운드를 선사하는 걸그룹.',
      en: 'A high-energy HEROINES group powering through reality with sweet, confident tunes.',
    },
    officialSite: 'https://heroines.jp/artist/nonfic',
    ticketUrl: 'https://ticketdive.com/artist/nonfic',
    chekiUrl: 'https://heroines.stores.jp/',
    scheduleUrl: 'https://heroines.jp/schedule',
    x: 'https://x.com/Nonfic_official',
    instagram: 'https://www.instagram.com/nonfic_official/',
    tiktok: 'https://www.tiktok.com/@nonfic_official',
    youtube: 'https://www.youtube.com/@Nonfic_official',
    subUnits: [],
    members: [
      {
        id: 'nf-koi-mizuki',
        groupId: 'nonfic',
        subUnitId: '',
        name: { ja: { kanji: '恋星はるか', kana: 'このほし はるか' }, ko: { hangul: '코노호시 하루카' }, en: { romaji: 'Haruka Konohoshi' } },
        memberColor: '#EC4899',
        memberColorName: { ja: 'ピンク', ko: '핑크', en: 'Pink' },
        imageUrl: '/images/members/nf-koi-mizuki.svg',
        birthDate: '2001-05-18',
        birthplace: { ja: '東京都', ko: '도쿄도', en: 'Tokyo' },
        nickname: { ja: 'はるちゃん', ko: '하루짱', en: 'Haru-chan' },
        links: [
          { type: 'x', url: 'https://x.com/haruka_nonfic', label: { ja: 'X (Twitter)', ko: '공식 X', en: 'Official X' }, verified: true, isPrimary: true },
        ],
      },
    ],
  },

  // ==========================================
  // [8] 도쿄 - 시부야: Appare!
  // ==========================================
  {
    id: 'appare',
    name: { ja: 'Appare!', ko: '앗파레 (Appare!)', en: 'Appare!' },
    shortName: { ja: 'あっぱれ', ko: '앗파레', en: 'Appare!' },
    agency: 'Appare! Project (HEROINES)',
    region: 'tokyo',
    district: 'shibuya',
    color: '#FFB800',
    accentColor: '#FFF3D6',
    debutYear: 2016,
    imageUrl: '/images/groups/appare.svg',
    description: {
      ja: '「天晴れ！」な熱量と圧倒的なダンス・ライブパフォーマンスで大型フェスを沸かせる最強ライブアイドル。',
      ko: '「앗파레(대단해)!」한 열량과 압도적인 댄스 및 라이브 퍼포먼스로 대형 페스티벌을 장악하는 최강 라이브 아이돌.',
      en: 'A high-energy live idol group dominating festivals with unmatched dance and energetic performances.',
    },
    officialSite: 'https://appare-official.jp/',
    ticketUrl: 'https://ticketdive.com/artist/appare',
    chekiUrl: 'https://appare1.thebase.in/',
    scheduleUrl: 'https://appare-official.jp/schedule/',
    x: 'https://x.com/official_appare',
    instagram: 'https://www.instagram.com/appare_official/',
    tiktok: 'https://www.tiktok.com/@official_appare',
    youtube: 'https://www.youtube.com/@appare_official',
    subUnits: [],
    members: [
      {
        id: 'appare-asahina-rei',
        groupId: 'appare',
        subUnitId: '',
        name: { ja: { kanji: '朝比奈れい', kana: 'あさひな れい' }, ko: { hangul: '아사히나 레이' }, en: { romaji: 'Rei Asahina' } },
        memberColor: '#E60012',
        memberColorName: { ja: '赤色', ko: '레드', en: 'Red' },
        imageUrl: '/images/members/appare-asahina-rei.svg',
        birthDate: '2000-03-17',
        birthplace: { ja: '東京都', ko: '도쿄도', en: 'Tokyo' },
        nickname: { ja: 'れいちゃん', ko: '레이짱', en: 'Rei-chan' },
        links: [
          { type: 'x', url: 'https://x.com/appare_rei', label: { ja: 'X (Twitter)', ko: '공식 X (트위터)', en: 'Official X' }, verified: true, isPrimary: true },
          { type: 'instagram', url: 'https://www.instagram.com/reiasahina/', label: { ja: 'Instagram', ko: '인스타그램', en: 'Instagram' }, verified: true, isPrimary: true },
        ],
      },
      {
        id: 'appare-fujimiya-may',
        groupId: 'appare',
        subUnitId: '',
        name: { ja: { kanji: '藤宮めい', kana: 'ふじみや めい' }, ko: { hangul: '후지미야 메이' }, en: { romaji: 'Mei Fujimiya' } },
        memberColor: '#FFFFFF',
        memberColorName: { ja: '白色', ko: '화이트', en: 'White' },
        imageUrl: '/images/members/appare-fujimiya-may.svg',
        birthDate: '2001-09-28',
        birthplace: { ja: '埼玉県', ko: '사이타마현', en: 'Saitama' },
        nickname: { ja: 'めいめい', ko: '메이메이', en: 'Meimei' },
        links: [
          { type: 'x', url: 'https://x.com/appare_may', label: { ja: 'X (Twitter)', ko: '공식 X (트위터)', en: 'Official X' }, verified: true, isPrimary: true },
        ],
      },
    ],
  },

  // ==========================================
  // [9] 도쿄 - 시부야: GANG PARADE
  // ==========================================
  {
    id: 'gang-parade',
    name: { ja: 'GANG PARADE', ko: '갱 퍼레이드 (GANG PARADE)', en: 'GANG PARADE' },
    shortName: { ja: 'ギャンパレ', ko: '걘파레', en: 'GP' },
    agency: 'WACK',
    region: 'tokyo',
    district: 'shibuya',
    color: '#E6FF00',
    accentColor: '#1A1A1A',
    debutYear: 2014,
    imageUrl: '/images/groups/gang-parade.svg',
    description: {
      ja: '「みんなの遊び場」をコンセプトに活動するWACK所属の13人組アイドルグループ。',
      ko: '「모두의 놀이터」를 콘셉트로 활동하는 WACK 소속 13인조 라이브 아이돌 그룹.',
      en: 'A 13-member powerhouse idol group from WACK performing under the concept "Everyone\'s Playground".',
    },
    officialSite: 'https://gangparade.jp/',
    ticketUrl: 'https://w.pia.jp/t/gangparade/',
    chekiUrl: 'https://gangparade.stores.jp/',
    scheduleUrl: 'https://gangparade.jp/schedule/',
    x: 'https://x.com/GANG_PARADE',
    instagram: 'https://www.instagram.com/gang_parade_official/',
    tiktok: 'https://www.tiktok.com/@gang_parade',
    youtube: 'https://www.youtube.com/@GANGPARADE_official',
    subUnits: [],
    members: [
      {
        id: 'gp-yumeno-yua',
        groupId: 'gang-parade',
        subUnitId: '',
        name: { ja: { kanji: 'ユメノユア', kana: 'ゆめの ゆあ' }, ko: { hangul: '유메노 유아' }, en: { romaji: 'Yua Yumeno' } },
        memberColor: '#E6FF00',
        memberColorName: { ja: 'ネオンイエロー', ko: '네온 옐로우', en: 'Neon Yellow' },
        imageUrl: '/images/members/gp-yumeno-yua.svg',
        birthDate: '1996-03-27',
        birthplace: { ja: '神奈川県', ko: '가나가와현', en: 'Kanagawa' },
        nickname: { ja: 'ユアちゃん', ko: '유아짱', en: 'Yua-chan' },
        links: [
          { type: 'x', url: 'https://x.com/YUA_GANG', label: { ja: 'X (Twitter)', ko: '공식 X (트위터)', en: 'Official X' }, verified: true, isPrimary: true },
        ],
      },
      {
        id: 'gp-coco-partin',
        groupId: 'gang-parade',
        subUnitId: '',
        name: { ja: { kanji: 'ココ・パーティン・ココ', kana: 'ここ ぱーてぃん ここ' }, ko: { hangul: '코코 파틴 코코' }, en: { romaji: 'Coco Partin Coco' } },
        memberColor: '#FF4500',
        memberColorName: { ja: 'オレンジレッド', ko: '오렌지 레드', en: 'Orange Red' },
        imageUrl: '/images/members/gp-coco-partin.svg',
        birthDate: '1995-10-01',
        birthplace: { ja: '愛知県', ko: '아이치현', en: 'Aichi' },
        nickname: { ja: 'ココちゃん', ko: '코코짱', en: 'Coco-chan' },
        links: [
          { type: 'x', url: 'https://x.com/COCO_GANG', label: { ja: 'X (Twitter)', ko: '공식 X (트위터)', en: 'Official X' }, verified: true, isPrimary: true },
        ],
      },
    ],
  },

  // ==========================================
  // [10] 도쿄 - 시부야: Jams Collection
  // ==========================================
  {
    id: 'jams-collection',
    name: { ja: 'Jams Collection', ko: '잼스 컬렉션 (Jams Collection)', en: 'Jams Collection' },
    shortName: { ja: 'ジャムズ', ko: '잼스', en: 'Jams' },
    agency: 'RIZE PRODUCTION',
    region: 'tokyo',
    district: 'shibuya',
    color: '#06B6D4',
    accentColor: '#ECFEFF',
    debutYear: 2021,
    imageUrl: '/images/groups/jams-collection.svg',
    description: {
      ja: '「大好きな曲を詰め込んだコレクション」をテーマに、圧倒的なビジュアルとライブパフォーマンスで武道館単独公演も成功させた大人気グループ。',
      ko: '「가장 좋아하는 음악을 가득 담은 보물상자」를 테마로 부도칸 단독 공연까지 성공시킨 대인기 라이브 아이돌 걸그룹.',
      en: 'A powerhouse idol group with stellar visuals and festival presence that headlined Nippon Budokan.',
    },
    officialSite: 'https://jamscollection.jp/',
    ticketUrl: 'https://ticketdive.com/artist/jamscollection',
    chekiUrl: 'https://jamscollection.stores.jp/',
    scheduleUrl: 'https://jamscollection.jp/schedule/',
    x: 'https://x.com/JamsCollection',
    instagram: 'https://www.instagram.com/jamscollection.official/',
    tiktok: 'https://www.tiktok.com/@jamscollection_official',
    youtube: 'https://www.youtube.com/@jamscollection',
    subUnits: [],
    members: [
      {
        id: 'jc-tsuda-nanami',
        groupId: 'jams-collection',
        subUnitId: '',
        name: { ja: { kanji: '津代美月', kana: 'つしろ みづき' }, ko: { hangul: '츠시로 미즈키' }, en: { romaji: 'Mizuki Tsushiro' } },
        memberColor: '#800080',
        memberColorName: { ja: '紫', ko: '퍼플', en: 'Purple' },
        imageUrl: '/images/members/jc-tsuda-nanami.svg',
        birthDate: '2000-10-16',
        birthplace: { ja: '大阪府', ko: '오사카부', en: 'Osaka' },
        nickname: { ja: 'ツシロ', ko: '츠시로', en: 'Tsushiro' },
        links: [
          { type: 'x', url: 'https://x.com/mizuki_jams', label: { ja: 'X (Twitter)', ko: '공식 X', en: 'Official X' }, verified: true, isPrimary: true },
        ],
      },
    ],
  },

  // ==========================================
  // [11] 도쿄 - 아키하바라: でんぱ組.inc
  // ==========================================
  {
    id: 'dempagumi',
    name: { ja: 'でんぱ組.inc', ko: '덴파구미.inc (Dempagumi.inc)', en: 'Dempagumi.inc' },
    shortName: { ja: 'でんぱ組', ko: '덴파구미', en: 'Dempa' },
    agency: 'DEARSTAGE',
    region: 'tokyo',
    district: 'akihabara',
    color: '#00E5FF',
    accentColor: '#E0F7FA',
    debutYear: 2008,
    imageUrl: '/images/groups/dempagumi.svg',
    description: {
      ja: '秋葉原ディアステージ発、アニメ・マンガ・ゲームなどオタクカルチャーを世界へ発信し続けた伝説的カルチャーアイドル。',
      ko: '아키하바라 디어스테이지 출신, 서브컬처 문화를 전 세계로 전파한 전설적인 아키바계 아이돌 걸그룹.',
      en: 'Originating from Akihabara DearStage, a legendary pioneer of modern otaku-culture live idols.',
    },
    officialSite: 'https://dempagumi.tokyo/',
    ticketUrl: 'https://t.livepocket.jp/p/dearstage',
    chekiUrl: 'https://dspmstore.com/shopbrand/dempa/',
    scheduleUrl: 'https://dempagumi.tokyo/schedule/',
    x: 'https://x.com/dempagumi',
    instagram: 'https://www.instagram.com/dempagumi.official/',
    tiktok: 'https://www.tiktok.com/@dempagumi_official',
    youtube: 'https://www.youtube.com/@dempagumi',
    subUnits: [],
    members: [
      {
        id: 'dempa-furukawa-mirin',
        groupId: 'dempagumi',
        subUnitId: '',
        name: { ja: { kanji: '古川未鈴', kana: 'ふるかわ みりん' }, ko: { hangul: '후루카와 미린' }, en: { romaji: 'Mirin Furukawa' } },
        memberColor: '#E60012',
        memberColorName: { ja: 'みりんレッド', ko: '미린 레드', en: 'Mirin Red' },
        imageUrl: '/images/members/dempa-furukawa-mirin.svg',
        birthDate: '1987-09-19',
        birthplace: { ja: '香川県', ko: '가가와현', en: 'Kagawa' },
        nickname: { ja: 'みりんちゃん', ko: '미린짱', en: 'Mirin-chan' },
        links: [
          { type: 'x', url: 'https://x.com/FurukawaMirin', label: { ja: 'X (Twitter)', ko: '공식 X (트위터)', en: 'Official X' }, verified: true, isPrimary: true },
        ],
      },
      {
        id: 'dempa-aizawa-risa',
        groupId: 'dempagumi',
        subUnitId: '',
        name: { ja: { kanji: '相沢梨紗', kana: 'あいざわ りさ' }, ko: { hangul: '아이자와 리사' }, en: { romaji: 'Risa Aizawa' } },
        memberColor: '#FFFFFF',
        memberColorName: { ja: 'りさホワイト', ko: '리사 화이트', en: 'Risa White' },
        imageUrl: '/images/members/dempa-aizawa-risa.svg',
        birthDate: '1988-08-02',
        birthplace: { ja: '大阪府', ko: '오사카부', en: 'Osaka' },
        nickname: { ja: 'りさちー', ko: '리사치', en: 'Risachee' },
        links: [
          { type: 'x', url: 'https://x.com/RISA_memesama', label: { ja: 'X (Twitter)', ko: '공식 X (트위터)', en: 'Official X' }, verified: true, isPrimary: true },
        ],
      },
    ],
  },

  // ==========================================
  // [12] 도쿄 - 아키하바라: 虹のコンキスタドール (2zicon)
  // ==========================================
  {
    id: '2zicon',
    name: { ja: '虹のコンキスタドール', ko: '니지의 콘키스타도르 (2zicon)', en: 'Niji no Conquistador' },
    shortName: { ja: '虹コン', ko: '니지콘', en: '2zicon' },
    agency: 'DEARSTAGE',
    region: 'tokyo',
    district: 'akihabara',
    color: '#F59E0B',
    accentColor: '#FEF3C7',
    debutYear: 2014,
    imageUrl: '/images/groups/2zicon.svg',
    description: {
      ja: '「毎日が夏休み！」をテーマに爽快なサマーソングとオタクカルチャーを発信するDEARSTAGEの看板グループ。',
      ko: '「매일이 여름방학!」을 테마로 상쾌한 서머 송과 다채로운 매력을 선보이는 DEARSTAGE 간판 걸그룹.',
      en: 'A prominent DEARSTAGE idol group renowned for uplifting summer anthems.',
    },
    officialSite: 'https://2zicon.tokyo/',
    ticketUrl: 'https://l-tike.com/2zicon/',
    chekiUrl: 'https://dspmstore.com/shopbrand/2zicon/',
    scheduleUrl: 'https://2zicon.tokyo/schedule/',
    x: 'https://x.com/2zicon',
    instagram: 'https://www.instagram.com/2zicon/',
    tiktok: 'https://www.tiktok.com/@2zicon',
    youtube: 'https://www.youtube.com/@2zicon',
    subUnits: [],
    members: [
      {
        id: '2z-tsurumi-moe',
        groupId: '2zicon',
        subUnitId: '',
        name: { ja: { kanji: '鶴見萌', kana: 'つるみ もえ' }, ko: { hangul: '츠루미 모에' }, en: { romaji: 'Moe Tsurumi' } },
        memberColor: '#9333EA',
        memberColorName: { ja: '紫', ko: '퍼플', en: 'Purple' },
        imageUrl: '/images/members/2z-tsurumi-moe.svg',
        birthDate: '1996-12-05',
        birthplace: { ja: '東京都', ko: '도쿄도', en: 'Tokyo' },
        nickname: { ja: 'もえ先輩', ko: '모에선배', en: 'Moe-senpai' },
        links: [
          { type: 'x', url: 'https://x.com/tsurumi_moe', label: { ja: 'X (Twitter)', ko: '공식 X', en: 'Official X' }, verified: true, isPrimary: true },
        ],
      },
    ],
  },

  // ==========================================
  // [13] 도쿄 - 아키하바라: FES☆TIVE
  // ==========================================
  {
    id: 'festive',
    name: { ja: 'FES☆TIVE', ko: '페스티브 (FES☆TIVE)', en: 'FES☆TIVE' },
    shortName: { ja: 'フェスティブ', ko: '페스티브', en: 'FESTIVE' },
    agency: 'RIZE PRODUCTION',
    region: 'tokyo',
    district: 'akihabara',
    color: '#EF4444',
    accentColor: '#FEE2E2',
    debutYear: 2013,
    imageUrl: '/images/groups/festive.svg',
    description: {
      ja: '「お祭り系アイドル」として「OIDEMASE!!〜極楽〜」など日本全国・世界各地のフェスで熱狂の渦を巻き起こす最強ライブグループ。',
      ko: '「축제계 아이돌」로서 「오이데마세! 극락」 등 전 세계 페스티벌을 열광의 도가니로 만드는 페스티벌 최강자.',
      en: 'The festival specialist idol group driving crowds wild with high-energy traditional Japanese dance fusion beats.',
    },
    officialSite: 'https://festive.rizep.net/',
    ticketUrl: 'https://ticketdive.com/artist/festive',
    chekiUrl: 'https://festive.stores.jp/',
    scheduleUrl: 'https://festive.rizep.net/schedule',
    x: 'https://x.com/FESTIVEofficial',
    instagram: 'https://www.instagram.com/festive_official/',
    tiktok: 'https://www.tiktok.com/@festive_official',
    youtube: 'https://www.youtube.com/@FESTIVE_official',
    subUnits: [],
    members: [
      {
        id: 'ft-aoba-hinata',
        groupId: 'festive',
        subUnitId: '',
        name: { ja: { kanji: '青葉ひなり', kana: 'あおば ひなり' }, ko: { hangul: '아오바 히나리' }, en: { romaji: 'Hinari Aoba' } },
        memberColor: '#EF4444',
        memberColorName: { ja: '赤', ko: '레드', en: 'Red' },
        imageUrl: '/images/members/ft-aoba-hinata.svg',
        birthDate: '1996-01-19',
        birthplace: { ja: '千葉県', ko: '지바현', en: 'Chiba' },
        nickname: { ja: 'ひなりん', ko: '히나린', en: 'Hinarin' },
        links: [
          { type: 'x', url: 'https://x.com/Hinari_FESTIVE', label: { ja: 'X (Twitter)', ko: '공식 X', en: 'Official X' }, verified: true, isPrimary: true },
        ],
      },
    ],
  },

  // ==========================================
  // [14] 간사이 / 오사카: カラフルスクリーム (Colorful Scream)
  // ==========================================
  {
    id: 'colorful-scream',
    name: { ja: 'カラフルスクリーム', ko: '컬러풀 스크림 (Colorful Scream)', en: 'Colorful Scream' },
    shortName: { ja: 'カラスク', ko: '카라스쿠', en: 'Karasuku' },
    agency: 'NTK Create',
    region: 'osaka',
    district: 'namba',
    color: '#00D26A',
    accentColor: '#E6F9F0',
    debutYear: 2017,
    imageUrl: '/images/groups/colorful-scream.svg',
    description: {
      ja: '関西・大阪を拠点に全国へポジティブな歌声を届ける、関西屈指の王道メロディック・ライブアイドル。',
      ko: '간사이・오사카를 거점으로 전국에 긍정적인 에너지를 전하는 오사카 대표 멜로딕 라이브 아이돌 걸그룹.',
      en: 'A premier melodic live idol group based in Osaka, Kansai bringing uplifting energy nationwide.',
    },
    officialSite: 'https://colorfulscream.com/',
    ticketUrl: 'https://tiget.net/users/77864',
    chekiUrl: 'https://colorfulscream.stores.jp/',
    scheduleUrl: 'https://colorfulscream.com/schedule/',
    x: 'https://x.com/colorful_scream',
    instagram: 'https://www.instagram.com/colorfulscream_official/',
    tiktok: 'https://www.tiktok.com/@colorfulscream_official',
    youtube: 'https://www.youtube.com/@colorfulscream_official',
    subUnits: [],
    members: [
      {
        id: 'karasuku-nako',
        groupId: 'colorful-scream',
        subUnitId: '',
        name: { ja: { kanji: 'なこ', kana: 'なこ' }, ko: { hangul: '나코' }, en: { romaji: 'Nako' } },
        memberColor: '#FF69B4',
        memberColorName: { ja: 'ピンク', ko: '핑크', en: 'Pink' },
        imageUrl: '/images/members/karasuku-nako.svg',
        birthDate: '1998-07-18',
        birthplace: { ja: '大阪府', ko: '오사카부', en: 'Osaka' },
        nickname: { ja: 'なこちゃん', ko: '나코짱', en: 'Nako-chan' },
        links: [
          { type: 'x', url: 'https://x.com/nako_colorful', label: { ja: 'X (Twitter)', ko: '공식 X (트위터)', en: 'Official X' }, verified: true, isPrimary: true },
        ],
      },
    ],
  },

  // ==========================================
  // [15] 간사이 / 오사카: Kolokol (콜로콜)
  // ==========================================
  {
    id: 'kolokol',
    name: { ja: 'Kolokol', ko: '콜로콜 (Kolokol)', en: 'Kolokol' },
    shortName: { ja: 'コロコル', ko: '콜로콜', en: 'Kolokol' },
    agency: 'we-B studios (Osaka)',
    region: 'osaka',
    district: 'namba',
    color: '#6366F1',
    accentColor: '#EEF2FF',
    debutYear: 2018,
    imageUrl: '/images/groups/kolokol.svg',
    description: {
      ja: '「囚われない音楽」をコンセプトに、美しいメロディと世界観で関西から全国のロックファンを魅了する実力派グループ。',
      ko: '「얽매이지 않는 음악」을 콘셉트로 서정적인 멜로디와 독보적인 라이브 실력을 자랑하는 간사이의 명품 걸그룹.',
      en: 'An acclaimed Osaka-based live idol group crafting intricate and beautiful indie-rock melodies.',
    },
    officialSite: 'https://kolokol-official.com/',
    ticketUrl: 'https://t.livepocket.jp/t/kolokol',
    chekiUrl: 'https://kolokol.stores.jp/',
    scheduleUrl: 'https://kolokol-official.com/schedule/',
    x: 'https://x.com/klkl_official',
    instagram: 'https://www.instagram.com/kolokol_official/',
    tiktok: null,
    youtube: 'https://www.youtube.com/@Kolokol_official',
    subUnits: [],
    members: [
      {
        id: 'kl-takahashi-saki',
        groupId: 'kolokol',
        subUnitId: '',
        name: { ja: { kanji: '高橋あきほ', kana: 'たかはし あきほ' }, ko: { hangul: '타카하시 아키호' }, en: { romaji: 'Akiho Takahashi' } },
        memberColor: '#6366F1',
        memberColorName: { ja: '青', ko: '블루', en: 'Blue' },
        imageUrl: '/images/members/kl-takahashi-saki.svg',
        birthDate: '1999-03-02',
        birthplace: { ja: '大阪府', ko: '오사카부', en: 'Osaka' },
        nickname: { ja: 'あきほ', ko: '아키호', en: 'Akiho' },
        links: [
          { type: 'x', url: 'https://x.com/akiho_klkl', label: { ja: 'X (Twitter)', ko: '공식 X', en: 'Official X' }, verified: true, isPrimary: true },
        ],
      },
    ],
  },

  // ==========================================
  // [16] 홋카이도 / 삿포로: タイトル未定 (Title Mitei)
  // ==========================================
  {
    id: 'title-mitei',
    name: { ja: 'タイトル未定', ko: '타이틀 미정 (Title Mitei)', en: 'Title Mitei' },
    shortName: { ja: '未定', ko: '미정', en: 'Mitei' },
    agency: 'TSUIMA Inc. (Sapporo)',
    region: 'sapporo',
    district: 'susukino',
    color: '#80BFFF',
    accentColor: '#F0F7FF',
    debutYear: 2020,
    imageUrl: '/images/groups/title-mitei.svg',
    description: {
      ja: '「何者かになろうとしなくていい」をテーマに、北海道・札幌から透明感ある叙情的な楽曲を届ける実力派グループ。',
      ko: '「무엇이 되려 하지 않아도 괜찮아」를 테마로 홋카이도 삿포로에서 투명하고 서정적인 음악을 선보이는 감성 실력파 걸그룹.',
      en: 'A critically acclaimed Sapporo-based idol group known for poetic music and emotional live performances.',
    },
    officialSite: 'https://miteititle.com/',
    ticketUrl: 'https://t.livepocket.jp/t/miteititle',
    chekiUrl: 'https://miteititle.stores.jp/',
    scheduleUrl: 'https://miteititle.com/schedule/',
    x: 'https://x.com/MiteiTitle',
    instagram: 'https://www.instagram.com/miteititle/',
    tiktok: 'https://www.tiktok.com/@miteititle',
    youtube: 'https://www.youtube.com/@miteititle',
    subUnits: [],
    members: [
      {
        id: 'mitei-abe-hana',
        groupId: 'title-mitei',
        subUnitId: '',
        name: { ja: { kanji: '阿部葉菜', kana: 'あべ はな' }, ko: { hangul: '아베 하나' }, en: { romaji: 'Hana Abe' } },
        memberColor: '#FFD700',
        memberColorName: { ja: 'イエロー', ko: '옐로우', en: 'Yellow' },
        imageUrl: '/images/members/mitei-abe-hana.svg',
        birthDate: '2000-01-27',
        birthplace: { ja: '北海道', ko: '홋카이도', en: 'Hokkaido' },
        nickname: { ja: 'はなちゃん', ko: '하나짱', en: 'Hana-chan' },
        links: [
          { type: 'x', url: 'https://x.com/hana_mitei', label: { ja: 'X (Twitter)', ko: '공식 X (트위터)', en: 'Official X' }, verified: true, isPrimary: true },
        ],
      },
    ],
  },

  // ==========================================
  // [17] 큐슈 / 후쿠오카: LinQ (링크)
  // ==========================================
  {
    id: 'linq',
    name: { ja: 'LinQ', ko: '링크 (LinQ)', en: 'LinQ' },
    shortName: { ja: 'リンク', ko: '링크', en: 'LinQ' },
    agency: 'IQ Project (Fukuoka)',
    region: 'fukuoka',
    district: 'tenjin',
    color: '#E60012',
    accentColor: '#FEE2E2',
    debutYear: 2011,
    imageUrl: '/images/groups/linq.svg',
    description: {
      ja: '「Love in 九州」を掲げ、福岡・天神を拠点に全国・アジアへ笑顔を届ける九州を代表する長寿アイドルグループ。',
      ko: '「Love in 큐슈」를 모토로 후쿠오카 텐진을 거점으로 전국과 아시아로 뻗어나가는 큐슈 대표 아이돌 걸그룹.',
      en: 'Fukuoka\'s premier Kyushu idol group representing Asian regional idol culture.',
    },
    officialSite: 'https://loveinq.com/',
    ticketUrl: 'https://tiget.net/users/5801',
    chekiUrl: 'https://linq.official.ec/',
    scheduleUrl: 'https://loveinq.com/schedule/',
    x: 'https://x.com/LinQ_official',
    instagram: 'https://www.instagram.com/linq_official/',
    tiktok: 'https://www.tiktok.com/@linq_official',
    youtube: 'https://www.youtube.com/@LinQ_official',
    subUnits: [],
    members: [
      {
        id: 'linq-takaki-yuumi',
        groupId: 'linq',
        subUnitId: '',
        name: { ja: { kanji: '高木悠未', kana: 'たかき ゆうみ' }, ko: { hangul: '타카키 유우미' }, en: { romaji: 'Yuumi Takaki' } },
        memberColor: '#E60012',
        memberColorName: { ja: 'パッションレッド', ko: '패션 레드', en: 'Passion Red' },
        imageUrl: '/images/members/linq-takaki-yuumi.svg',
        birthDate: '1997-05-17',
        birthplace: { ja: '福岡県', ko: '후쿠오카현', en: 'Fukuoka' },
        nickname: { ja: 'ゆうみん', ko: '유우민', en: 'Yuumin' },
        links: [
          { type: 'x', url: 'https://x.com/yuumi_takaki', label: { ja: 'X (Twitter)', ko: '공식 X (트위터)', en: 'Official X' }, verified: true, isPrimary: true },
        ],
      },
    ],
  },

  // ==========================================
  // [18] 토카이 / 나고야: 手羽先センセーション (테바사키 센세이션)
  // ==========================================
  {
    id: 'tebasen',
    name: { ja: '手羽先センセーション', ko: '테바사키 센세이션 (Tebasaki Sensation)', en: 'Tebasaki Sensation' },
    shortName: { ja: '手羽セン', ko: '테바센', en: 'TebaSen' },
    agency: 'FreeK-Laboratory (Nagoya)',
    region: 'nagoya',
    district: 'sakae',
    color: '#FF8C00',
    accentColor: '#FFF7ED',
    debutYear: 2017,
    imageUrl: '/images/groups/tebasen.svg',
    description: {
      ja: '「手羽先のように愛されるグループ」を目指し、名古屋・栄を拠点に圧倒的なライブの熱気と王道ポップを届ける名古屋の代表格。',
      ko: '「나고야 명물 테바사키처럼 모두에게 사랑받는 아이돌」을 목표로 나고야 사카에를 거점으로 왕도 팝을 선보이는 나고야 대표 걸그룹.',
      en: 'Nagoya\'s iconic energetic idol sensation bringing melodic pop songs from Sakae, Nagoya.',
    },
    officialSite: 'https://www.tebasen.com/',
    ticketUrl: 'https://t.livepocket.jp/t/tebasen',
    chekiUrl: 'https://tebasen.stores.jp/',
    scheduleUrl: 'https://www.tebasen.com/schedule/',
    x: 'https://x.com/teba_sen',
    instagram: 'https://www.instagram.com/teba_sen/',
    tiktok: 'https://www.tiktok.com/@teba_sen',
    youtube: 'https://www.youtube.com/@tebasen',
    subUnits: [],
    members: [
      {
        id: 'tebasen-hinami-haruka',
        groupId: 'tebasen',
        subUnitId: '',
        name: { ja: { kanji: '日南遥', kana: 'ひなみ はるか' }, ko: { hangul: '히나미 하루카' }, en: { romaji: 'Haruka Hinami' } },
        memberColor: '#FF8C00',
        memberColorName: { ja: 'オレンジ', ko: '오렌지', en: 'Orange' },
        imageUrl: '/images/members/tebasen-hinami-haruka.svg',
        birthDate: '1999-01-24',
        birthplace: { ja: '愛知県', ko: '아이치현', en: 'Aichi' },
        nickname: { ja: 'はるちゃん', ko: '하루짱', en: 'Haru-chan' },
        links: [
          { type: 'x', url: 'https://x.com/haruka_tebasen', label: { ja: 'X (Twitter)', ko: '공식 X (트위터)', en: 'Official X' }, verified: true, isPrimary: true },
        ],
      },
    ],
  },
];

function seed() {
  const dataDir = path.join(__dirname, '..', 'data');
  if (!fs.existsSync(dataDir)) fs.mkdirSync(dataDir, { recursive: true });

  const outPath = path.join(dataDir, 'chika-groups.json');
  fs.writeFileSync(outPath, JSON.stringify(CHIKA_GROUPS_EXPANDED, null, 2), 'utf-8');
  console.log(`✅ Seeded ${CHIKA_GROUPS_EXPANDED.length} verified real girl groups to data/chika-groups.json`);
}

seed();
