import * as fs from 'fs';
import * as path from 'path';
import type { ChikaGroup, ChikaNotice, GravureFeature } from '../src/lib/schema';

export const CHIKA_GROUPS_COMPLETE: ChikaGroup[] = [
  // ==========================================
  // [1] FRUITS ZIPPER (하라주쿠)
  // ==========================================
  {
    id: 'fruits-zipper',
    name: { ja: 'FRUITS ZIPPER', ko: '후르츠 지퍼 (FRUITS ZIPPER)', en: 'FRUITS ZIPPER' },
    shortName: { ja: 'ふるっぱー', ko: '후룹파', en: 'FZ' },
    agency: 'ASOBISYSTEM (KAWAII LAB.)',
    region: 'tokyo',
    district: 'harajuku',
    color: '#FF6EA7',
    accentColor: '#FFE5EC',
    debutYear: 2022,
    imageUrl: '/images/groups/fruits-zipper.svg',
    xFollowers: 285000,
    popularityScore: 99,
    searchVolumeScore: 98,
    description: {
      ja: '「原宿から世界へ」をコンセプトに、「わたしの一番かわいいところ」がTikTok 9億再生を突破したKAWAII LAB.の第1弾フラッグシップグループ。',
      ko: '「하라주쿠에서 세계로」를 콘셉트로 「내가 가장 귀여운 곳」이 틱톡 9억 뷰를 돌파한 카와이 랩의 제1탄 대표 걸그룹.',
      en: 'The flagship breakthrough idol group of KAWAII LAB. transmitting Harajuku kawaii culture worldwide.',
    },
    officialSite: 'https://fruitszipper.asobisystem.com/',
    ticketUrl: 'https://l-tike.com/fruitszipper/',
    chekiUrl: 'https://kawaiilab.stores.jp/',
    scheduleUrl: 'https://fruitszipper.asobisystem.com/schedule/',
    x: 'https://x.com/fruits_zipper',
    instagram: 'https://www.instagram.com/fruits_zipper/',
    tiktok: 'https://www.tiktok.com/@fruits_zipper',
    youtube: 'https://www.youtube.com/@fruitszipper3799',
    subUnits: [],
    members: [
      {
        id: 'fz-matsumoto-karen',
        groupId: 'fruits-zipper',
        subUnitId: '',
        name: { ja: { kanji: '松本かれん', kana: 'まつもと かれん' }, ko: { hangul: '마츠모토 카렌' }, en: { romaji: 'Karen Matsumoto' } },
        memberColor: '#FFA7C4',
        memberColorName: { ja: 'ベビーピンク', ko: '베이비 핑크', en: 'Baby Pink' },
        imageUrl: '/images/members/fz-matsumoto-karen.svg',
        birthDate: '2002-03-28',
        birthplace: { ja: '千葉県', ko: '지바현', en: 'Chiba' },
        nickname: { ja: 'かれんたん', ko: '카렌탄', en: 'Karentan' },
        xFollowers: 195000,
        igFollowers: 320000,
        popularityScore: 99,
        searchVolumeScore: 98,
        isGravureActive: true,
        gravureHighlights: ['週刊ヤングジャンプ 表紙', 'LARME レギュラーモデル'],
        links: [
          { type: 'x', url: 'https://x.com/karen_fz0328', label: { ja: 'X (Twitter)', ko: '공식 X', en: 'Official X' }, verified: true, isPrimary: true },
          { type: 'instagram', url: 'https://www.instagram.com/karen_matsumoto_/', label: { ja: 'Instagram', ko: '인스타그램', en: 'Instagram' }, verified: true, isPrimary: true },
        ],
      },
      {
        id: 'fz-sakurai-yui',
        groupId: 'fruits-zipper',
        subUnitId: '',
        name: { ja: { kanji: '櫻井優衣', kana: 'さくらい ゆい' }, ko: { hangul: '사쿠라이 유이' }, en: { romaji: 'Yui Sakurai' } },
        memberColor: '#72D792',
        memberColorName: { ja: 'ミントグリーン', ko: '민트 그린', en: 'Mint Green' },
        imageUrl: '/images/members/fz-sakurai-yui.svg',
        birthDate: '2000-02-21',
        birthplace: { ja: '東京都', ko: '도쿄도', en: 'Tokyo' },
        nickname: { ja: 'ゆいちゃん', ko: '유이짱', en: 'Yui-chan' },
        xFollowers: 188000,
        igFollowers: 290000,
        popularityScore: 98,
        searchVolumeScore: 96,
        isGravureActive: true,
        gravureHighlights: ['1st写真集「YUi」大ヒット', '週刊プレイボーイ 表紙巻頭グラビア'],
        links: [
          { type: 'x', url: 'https://x.com/yui_fz0221', label: { ja: 'X (Twitter)', ko: '공식 X', en: 'Official X' }, verified: true, isPrimary: true },
          { type: 'instagram', url: 'https://www.instagram.com/yui.sakurai_7/', label: { ja: 'Instagram', ko: '인스타그램', en: 'Instagram' }, verified: true, isPrimary: true },
        ],
      },
      {
        id: 'fz-chinzei-suzuka',
        groupId: 'fruits-zipper',
        subUnitId: '',
        name: { ja: { kanji: '鎮西寿々歌', kana: 'ちんぜい すずか' }, ko: { hangul: '친제이 스즈카' }, en: { romaji: 'Suzuka Chinzei' } },
        memberColor: '#FF9E40',
        memberColorName: { ja: 'オレンジ', ko: '오렌지', en: 'Orange' },
        imageUrl: '/images/members/fz-chinzei-suzuka.svg',
        birthDate: '1998-11-24',
        birthplace: { ja: '兵庫県', ko: '효고현', en: 'Hyogo' },
        nickname: { ja: 'おすず', ko: '오스즈', en: 'Osuzu' },
        xFollowers: 145000,
        igFollowers: 240000,
        popularityScore: 95,
        searchVolumeScore: 93,
        isGravureActive: false,
        gravureHighlights: [],
        links: [
          { type: 'x', url: 'https://x.com/suzuka_fz1124', label: { ja: 'X (Twitter)', ko: '공식 X', en: 'Official X' }, verified: true, isPrimary: true },
          { type: 'instagram', url: 'https://www.instagram.com/tarasuzuka24/', label: { ja: 'Instagram', ko: '인스타그램', en: 'Instagram' }, verified: true, isPrimary: true },
        ],
      },
    ],
  },

  // ==========================================
  // [2] CANDY TUNE (하라주쿠)
  // ==========================================
  {
    id: 'candy-tune',
    name: { ja: 'CANDY TUNE', ko: '캔디 튠 (CANDY TUNE)', en: 'CANDY TUNE' },
    shortName: { ja: 'きゃんちゅー', ko: '캔츄', en: 'CT' },
    agency: 'ASOBISYSTEM (KAWAII LAB.)',
    region: 'tokyo',
    district: 'harajuku',
    color: '#FF69B4',
    accentColor: '#FFE4E6',
    debutYear: 2023,
    imageUrl: '/images/groups/candy-tune.svg',
    xFollowers: 130000,
    popularityScore: 92,
    searchVolumeScore: 91,
    description: {
      ja: '「フレーフレー私！」などポップでキュートな王道アイドルソングを届けるKAWAII LAB.第2弾アイドルグループ。',
      ko: '「힘내라 나!」 등 톡톡 튀는 캔디 같은 사운드와 카와이 매력으로 주목받는 카와이 랩 제2탄 걸그룹.',
      en: 'The second idol group from KAWAII LAB. radiating colorful and energetic pop tunes.',
    },
    officialSite: 'https://candy-tune.asobisystem.com/',
    ticketUrl: 'https://l-tike.com/candytune/',
    chekiUrl: 'https://kawaiilab.stores.jp/',
    scheduleUrl: 'https://candy-tune.asobisystem.com/schedule/',
    x: 'https://x.com/CANDY_TUNE_',
    instagram: 'https://www.instagram.com/candy__tune/',
    tiktok: 'https://www.tiktok.com/@candy_tune',
    youtube: 'https://www.youtube.com/@CANDYTUNE',
    subUnits: [],
    members: [
      {
        id: 'ct-murakawa-bibian',
        groupId: 'candy-tune',
        subUnitId: '',
        name: { ja: { kanji: '村川緋杏', kana: 'むらかわ びびあん' }, ko: { hangul: '무라카와 비비안' }, en: { romaji: 'Bibian Murakawa' } },
        memberColor: '#FF69B4',
        memberColorName: { ja: 'ピンク', ko: '핑크', en: 'Pink' },
        imageUrl: '/images/members/ct-murakawa-bibian.svg',
        birthDate: '1999-12-03',
        birthplace: { ja: '福岡県', ko: '후쿠오카현', en: 'Fukuoka' },
        nickname: { ja: 'びびあん', ko: '비비안', en: 'Bibian' },
        xFollowers: 98000,
        igFollowers: 150000,
        popularityScore: 92,
        searchVolumeScore: 90,
        isGravureActive: false,
        gravureHighlights: [],
        links: [
          { type: 'x', url: 'https://x.com/bibian_ct1203', label: { ja: 'X (Twitter)', ko: '공식 X', en: 'Official X' }, verified: true, isPrimary: true },
        ],
      },
      {
        id: 'ct-kano-nanako',
        groupId: 'candy-tune',
        subUnitId: '',
        name: { ja: { kanji: '小川奈々子', kana: 'おがわ ななこ' }, ko: { hangul: '오가와 나나코' }, en: { romaji: 'Nanako Ogawa' } },
        memberColor: '#4169E1',
        memberColorName: { ja: 'ブルー', ko: '블루', en: 'Blue' },
        imageUrl: '/images/members/ct-kano-nanako.svg',
        birthDate: '1999-10-01',
        birthplace: { ja: '北海道', ko: '홋카이도', en: 'Hokkaido' },
        nickname: { ja: 'ななこ', ko: '나나코', en: 'Nanako' },
        xFollowers: 72000,
        igFollowers: 110000,
        popularityScore: 89,
        searchVolumeScore: 88,
        isGravureActive: true,
        gravureHighlights: ['ヤングガンガン 巻末グラビア'],
        links: [
          { type: 'x', url: 'https://x.com/nachico_ct1001', label: { ja: 'X (Twitter)', ko: '공식 X', en: 'Official X' }, verified: true, isPrimary: true },
        ],
      },
    ],
  },

  // ==========================================
  // [3] iLiFE! (신주쿠)
  // ==========================================
  {
    id: 'ilife',
    name: { ja: 'iLiFE!', ko: '아이라이프 (iLiFE!)', en: 'iLiFE!' },
    shortName: { ja: 'アイライフ', ko: '아이라이프', en: 'iLiFE!' },
    agency: 'HEROINES (imaginate)',
    region: 'tokyo',
    district: 'shinjuku',
    color: '#FF2E7E',
    accentColor: '#FFD6E5',
    debutYear: 2020,
    imageUrl: '/images/groups/ilife.svg',
    xFollowers: 220000,
    popularityScore: 98,
    searchVolumeScore: 99,
    description: {
      ja: '「私（i）と貴方（you）で創るアイドル（iLiFE!）」をコンセプトに、爆発的なライブ動員を誇るHEROINESのフラッグシップグループ。',
      ko: '「나(i)와 당신(you)이 함께 만드는 아이돌」을 콘셉트로 폭발적인 라이브 동원력을 자랑하는 HEROINES 대표 걸그룹.',
      en: 'The top flagship group of HEROINES creating explosive festival energy together with fans.',
    },
    officialSite: 'https://heroines.jp/artist/ilife',
    ticketUrl: 'https://ticketdive.com/artist/ilife',
    chekiUrl: 'https://heroines.stores.jp/',
    scheduleUrl: 'https://timetreeapp.com/public_calendars/ilife_official',
    x: 'https://x.com/iLiFE_official',
    instagram: 'https://www.instagram.com/ilife.heroines/',
    tiktok: 'https://www.tiktok.com/@ilife.heroines',
    youtube: 'https://www.youtube.com/@iLiFE_official',
    subUnits: [],
    members: [
      {
        id: 'ilife-shinzome-riri',
        groupId: 'ilife',
        subUnitId: '',
        name: { ja: { kanji: '心花りり', kana: 'しんぞめ りり' }, ko: { hangul: '신조메 리리' }, en: { romaji: 'Riri Shinzome' } },
        memberColor: '#E60033',
        memberColorName: { ja: '赤色', ko: '레드', en: 'Red' },
        imageUrl: '/images/members/ilife-shinzome-riri.svg',
        birthDate: '2000-05-19',
        birthplace: { ja: '神奈川県', ko: '가나가와현', en: 'Kanagawa' },
        nickname: { ja: 'りりちゃん', ko: '리리짱', en: 'Riri-chan' },
        xFollowers: 240000,
        igFollowers: 310000,
        popularityScore: 99,
        searchVolumeScore: 99,
        isGravureActive: true,
        gravureHighlights: ['ヤングジャンプ 表紙', 'ヤングアニマル 表紙巻頭'],
        links: [
          { type: 'x', url: 'https://x.com/iLiFE_riri', label: { ja: 'X (Twitter)', ko: '공식 X', en: 'Official X' }, verified: true, isPrimary: true },
          { type: 'instagram', url: 'https://www.instagram.com/riri_shinzome/', label: { ja: 'Instagram', ko: '인스타그램', en: 'Instagram' }, verified: true, isPrimary: true },
        ],
      },
      {
        id: 'ilife-aisu',
        groupId: 'ilife',
        subUnitId: '',
        name: { ja: { kanji: 'あいす', kana: 'あいす' }, ko: { hangul: '아이스' }, en: { romaji: 'Aisu' } },
        memberColor: '#B0E0E6',
        memberColorName: { ja: '白色・水色', ko: '화이트/라이트블루', en: 'White Light Blue' },
        imageUrl: '/images/members/ilife-aisu.svg',
        birthDate: '2006-01-24',
        birthplace: { ja: '東京都', ko: '도쿄도', en: 'Tokyo' },
        nickname: { ja: 'あいす', ko: '아이스', en: 'Aisu' },
        xFollowers: 210000,
        igFollowers: 280000,
        popularityScore: 97,
        searchVolumeScore: 97,
        isGravureActive: false,
        gravureHighlights: [],
        links: [
          { type: 'x', url: 'https://x.com/iLiFE_aisu', label: { ja: 'X (Twitter)', ko: '공식 X', en: 'Official X' }, verified: true, isPrimary: true },
          { type: 'instagram', url: 'https://www.instagram.com/aisu_ilife/', label: { ja: 'Instagram', ko: '인스타그램', en: 'Instagram' }, verified: true, isPrimary: true },
        ],
      },
    ],
  },

  // ==========================================
  // [4] Appare! (시부야)
  // ==========================================
  {
    id: 'appare',
    name: { ja: 'Appare!', ko: '앗파레 (Appare!)', en: 'Appare!' },
    shortName: { ja: 'あっぱれ', ko: '앗파레', en: 'Appare!' },
    agency: 'Appare! Project (HEROINES)',
    region: 'tokyo',
    district: 'shibuya',
    color: '#FFB800',
    accentColor: '#FFF3D6',
    debutYear: 2016,
    imageUrl: '/images/groups/appare.svg',
    xFollowers: 140000,
    popularityScore: 93,
    searchVolumeScore: 92,
    description: {
      ja: '「天晴れ！」な熱量と圧倒的なダンス・ライブパフォーマンスで大型フェスを沸かせる最強ライブアイドル。',
      ko: '「앗파레(대단해)!」한 열량과 압도적인 댄스 및 라이브 퍼포먼스로 대형 페스티벌을 장악하는 최강 라이브 아이돌.',
      en: 'A high-energy live idol group dominating festivals with unmatched dance and energetic performances.',
    },
    officialSite: 'https://appare-official.jp/',
    ticketUrl: 'https://ticketdive.com/artist/appare',
    chekiUrl: 'https://appare1.thebase.in/',
    scheduleUrl: 'https://appare-official.jp/schedule/',
    x: 'https://x.com/official_appare',
    instagram: 'https://www.instagram.com/appare_official/',
    tiktok: 'https://www.tiktok.com/@official_appare',
    youtube: 'https://www.youtube.com/@appare_official',
    subUnits: [],
    members: [
      {
        id: 'appare-asahina-rei',
        groupId: 'appare',
        subUnitId: '',
        name: { ja: { kanji: '朝比奈れい', kana: 'あさひな れい' }, ko: { hangul: '아사히나 레이' }, en: { romaji: 'Rei Asahina' } },
        memberColor: '#E60012',
        memberColorName: { ja: '赤色', ko: '레드', en: 'Red' },
        imageUrl: '/images/members/appare-asahina-rei.svg',
        birthDate: '2000-03-17',
        birthplace: { ja: '東京都', ko: '도쿄도', en: 'Tokyo' },
        nickname: { ja: 'れいちゃん', ko: '레이짱', en: 'Rei-chan' },
        xFollowers: 86000,
        igFollowers: 120000,
        popularityScore: 92,
        searchVolumeScore: 91,
        isGravureActive: true,
        gravureHighlights: ['週刊SPA! グラビア掲載'],
        links: [
          { type: 'x', url: 'https://x.com/appare_rei', label: { ja: 'X (Twitter)', ko: '공식 X', en: 'Official X' }, verified: true, isPrimary: true },
        ],
      },
    ],
  },

  // ==========================================
  // [5] でんぱ組.inc (아키하바라)
  // ==========================================
  {
    id: 'dempagumi',
    name: { ja: 'でんぱ組.inc', ko: '덴파구미.inc (Dempagumi.inc)', en: 'Dempagumi.inc' },
    shortName: { ja: 'でんぱ組', ko: '덴파구미', en: 'Dempa' },
    agency: 'DEARSTAGE',
    region: 'tokyo',
    district: 'akihabara',
    color: '#00E5FF',
    accentColor: '#E0F7FA',
    debutYear: 2008,
    imageUrl: '/images/groups/dempagumi.svg',
    xFollowers: 320000,
    popularityScore: 96,
    searchVolumeScore: 94,
    description: {
      ja: '秋葉原ディアステージ発、アニメ・マンガ・ゲームなどオタクカルチャーを世界へ発信し続けた伝説的カルチャーアイドル。',
      ko: '아키하바라 디어스테이지 출신, 서브컬처 문화를 전 세계로 전파한 전설적인 아키바계 아이돌 걸그룹.',
      en: 'Originating from Akihabara DearStage, a legendary pioneer of modern otaku-culture live idols.',
    },
    officialSite: 'https://dempagumi.tokyo/',
    ticketUrl: 'https://t.livepocket.jp/p/dearstage',
    chekiUrl: 'https://dspmstore.com/shopbrand/dempa/',
    scheduleUrl: 'https://dempagumi.tokyo/schedule/',
    x: 'https://x.com/dempagumi',
    instagram: 'https://www.instagram.com/dempagumi.official/',
    tiktok: 'https://www.tiktok.com/@dempagumi_official',
    youtube: 'https://www.youtube.com/@dempagumi',
    subUnits: [],
    members: [
      {
        id: 'dempa-furukawa-mirin',
        groupId: 'dempagumi',
        subUnitId: '',
        name: { ja: { kanji: '古川未鈴', kana: 'ふるかわ みりん' }, ko: { hangul: '후루카와 미린' }, en: { romaji: 'Mirin Furukawa' } },
        memberColor: '#E60012',
        memberColorName: { ja: 'みりんレッド', ko: '미린 레드', en: 'Mirin Red' },
        imageUrl: '/images/members/dempa-furukawa-mirin.svg',
        birthDate: '1987-09-19',
        birthplace: { ja: '香川県', ko: '가가와현', en: 'Kagawa' },
        nickname: { ja: 'みりんちゃん', ko: '미린짱', en: 'Mirin-chan' },
        xFollowers: 280000,
        igFollowers: 190000,
        popularityScore: 96,
        searchVolumeScore: 94,
        isGravureActive: false,
        gravureHighlights: [],
        links: [
          { type: 'x', url: 'https://x.com/FurukawaMirin', label: { ja: 'X (Twitter)', ko: '공식 X', en: 'Official X' }, verified: true, isPrimary: true },
        ],
      },
    ],
  },

  // ==========================================
  // [6] 虹のコンキスタドール (아키하바라)
  // ==========================================
  {
    id: '2zicon',
    name: { ja: '虹のコンキスタドール', ko: '니지의 콘키스타도르 (2zicon)', en: 'Niji no Conquistador' },
    shortName: { ja: '虹コン', ko: '니지콘', en: '2zicon' },
    agency: 'DEARSTAGE',
    region: 'tokyo',
    district: 'akihabara',
    color: '#F59E0B',
    accentColor: '#FEF3C7',
    debutYear: 2014,
    imageUrl: '/images/groups/2zicon.svg',
    xFollowers: 175000,
    popularityScore: 93,
    searchVolumeScore: 92,
    description: {
      ja: '「毎日が夏休み！」をテーマに爽快なサマーソングとオタクカルチャーを発信するDEARSTAGEの看板グループ。',
      ko: '「매일이 여름방학!」을 테마로 상쾌한 서머 송과 다채로운 매력을 선보이는 DEARSTAGE 간판 걸그룹.',
      en: 'A prominent DEARSTAGE idol group renowned for uplifting summer anthems.',
    },
    officialSite: 'https://2zicon.tokyo/',
    ticketUrl: 'https://l-tike.com/2zicon/',
    chekiUrl: 'https://dspmstore.com/shopbrand/2zicon/',
    scheduleUrl: 'https://2zicon.tokyo/schedule/',
    x: 'https://x.com/2zicon',
    instagram: 'https://www.instagram.com/2zicon/',
    tiktok: 'https://www.tiktok.com/@2zicon',
    youtube: 'https://www.youtube.com/@2zicon',
    subUnits: [],
    members: [
      {
        id: '2z-tsurumi-moe',
        groupId: '2zicon',
        subUnitId: '',
        name: { ja: { kanji: '鶴見萌', kana: 'つるみ もえ' }, ko: { hangul: '츠루미 모에' }, en: { romaji: 'Moe Tsurumi' } },
        memberColor: '#9333EA',
        memberColorName: { ja: '紫', ko: '퍼플', en: 'Purple' },
        imageUrl: '/images/members/2z-tsurumi-moe.svg',
        birthDate: '1996-12-05',
        birthplace: { ja: '東京都', ko: '도쿄도', en: 'Tokyo' },
        nickname: { ja: 'もえ先輩', ko: '모에선배', en: 'Moe-senpai' },
        xFollowers: 85000,
        igFollowers: 130000,
        popularityScore: 93,
        searchVolumeScore: 92,
        isGravureActive: true,
        gravureHighlights: ['ヤングアニマル 表紙巻頭グラビア', '写真集「つるみん」'],
        links: [
          { type: 'x', url: 'https://x.com/tsurumi_moe', label: { ja: 'X (Twitter)', ko: '공식 X', en: 'Official X' }, verified: true, isPrimary: true },
        ],
      },
    ],
  },

  // ==========================================
  // [7] FES☆TIVE (아키하바라)
  // ==========================================
  {
    id: 'festive',
    name: { ja: 'FES☆TIVE', ko: '페스티브 (FES☆TIVE)', en: 'FES☆TIVE' },
    shortName: { ja: 'フェスティブ', ko: '페스티브', en: 'FESTIVE' },
    agency: 'RIZE PRODUCTION',
    region: 'tokyo',
    district: 'akihabara',
    color: '#EF4444',
    accentColor: '#FEE2E2',
    debutYear: 2013,
    imageUrl: '/images/groups/festive.svg',
    xFollowers: 110000,
    popularityScore: 91,
    searchVolumeScore: 90,
    description: {
      ja: '「お祭り系アイドル」として「OIDEMASE!!〜極楽〜」など日本全国・世界各地のフェスで熱狂の渦を巻き起こす最強ライブグループ。',
      ko: '「축제계 아이돌」로서 「오이데마세! 극락」 등 전 세계 페스티벌을 열광의 도가니로 만드는 페스티벌 최강자.',
      en: 'The festival specialist idol group driving crowds wild with high-energy traditional Japanese dance fusion beats.',
    },
    officialSite: 'https://festive.rizep.net/',
    ticketUrl: 'https://ticketdive.com/artist/festive',
    chekiUrl: 'https://festive.stores.jp/',
    scheduleUrl: 'https://festive.rizep.net/schedule',
    x: 'https://x.com/FESTIVEofficial',
    instagram: 'https://www.instagram.com/festive_official/',
    tiktok: 'https://www.tiktok.com/@festive_official',
    youtube: 'https://www.youtube.com/@FESTIVE_official',
    subUnits: [],
    members: [
      {
        id: 'ft-aoba-hinata',
        groupId: 'festive',
        subUnitId: '',
        name: { ja: { kanji: '青葉ひなり', kana: 'あおば ひなり' }, ko: { hangul: '아오바 히나리' }, en: { romaji: 'Hinari Aoba' } },
        memberColor: '#EF4444',
        memberColorName: { ja: '赤', ko: '레드', en: 'Red' },
        imageUrl: '/images/members/ft-aoba-hinata.svg',
        birthDate: '1996-01-19',
        birthplace: { ja: '千葉県', ko: '지바현', en: 'Chiba' },
        nickname: { ja: 'ひなりん', ko: '히나린', en: 'Hinarin' },
        xFollowers: 95000,
        igFollowers: 140000,
        popularityScore: 91,
        searchVolumeScore: 90,
        isGravureActive: true,
        gravureHighlights: ['ヤングチャンピオン 表紙', '1st写真集「ひなりん」'],
        links: [
          { type: 'x', url: 'https://x.com/Hinari_FESTIVE', label: { ja: 'X (Twitter)', ko: '공식 X', en: 'Official X' }, verified: true, isPrimary: true },
        ],
      },
    ],
  },

  // ==========================================
  // [8] カラフルスクリーム (오사카)
  // ==========================================
  {
    id: 'colorful-scream',
    name: { ja: 'カラフルスクリーム', ko: '컬러풀 스크림 (Colorful Scream)', en: 'Colorful Scream' },
    shortName: { ja: 'カラスク', ko: '카라스쿠', en: 'Karasuku' },
    agency: 'NTK Create',
    region: 'osaka',
    district: 'namba',
    color: '#00D26A',
    accentColor: '#E6F9F0',
    debutYear: 2017,
    imageUrl: '/images/groups/colorful-scream.svg',
    xFollowers: 55000,
    popularityScore: 89,
    searchVolumeScore: 88,
    description: {
      ja: '関西・大阪を拠点に全国へポジティブな歌声を届ける、関西屈指の王道メロディック・ライブアイドル。',
      ko: '간사이・오사카를 거점으로 전국에 긍정적인 에너지를 전하는 오사카 대표 멜로딕 라이브 아이돌 걸그룹.',
      en: 'A premier melodic live idol group based in Osaka, Kansai bringing uplifting energy nationwide.',
    },
    officialSite: 'https://colorfulscream.com/',
    ticketUrl: 'https://tiget.net/users/77864',
    chekiUrl: 'https://colorfulscream.stores.jp/',
    scheduleUrl: 'https://colorfulscream.com/schedule/',
    x: 'https://x.com/colorful_scream',
    instagram: 'https://www.instagram.com/colorfulscream_official/',
    tiktok: 'https://www.tiktok.com/@colorfulscream_official',
    youtube: 'https://www.youtube.com/@colorfulscream_official',
    subUnits: [],
    members: [
      {
        id: 'karasuku-nako',
        groupId: 'colorful-scream',
        subUnitId: '',
        name: { ja: { kanji: 'なこ', kana: 'なこ' }, ko: { hangul: '나코' }, en: { romaji: 'Nako' } },
        memberColor: '#FF69B4',
        memberColorName: { ja: 'ピンク', ko: '핑크', en: 'Pink' },
        imageUrl: '/images/members/karasuku-nako.svg',
        birthDate: '1998-07-18',
        birthplace: { ja: '大阪府', ko: '오사카부', en: 'Osaka' },
        nickname: { ja: 'なこちゃん', ko: '나코짱', en: 'Nako-chan' },
        xFollowers: 32000,
        igFollowers: 45000,
        popularityScore: 89,
        searchVolumeScore: 88,
        isGravureActive: false,
        gravureHighlights: [],
        links: [
          { type: 'x', url: 'https://x.com/nako_colorful', label: { ja: 'X (Twitter)', ko: '공식 X (트위터)', en: 'Official X' }, verified: true, isPrimary: true },
        ],
      },
    ],
  },

  // ==========================================
  // [9] タイトル未定 (삿포로)
  // ==========================================
  {
    id: 'title-mitei',
    name: { ja: 'タイトル未定', ko: '타이틀 미정 (Title Mitei)', en: 'Title Mitei' },
    shortName: { ja: '未定', ko: '미정', en: 'Mitei' },
    agency: 'TSUIMA Inc. (Sapporo)',
    region: 'sapporo',
    district: 'susukino',
    color: '#80BFFF',
    accentColor: '#F0F7FF',
    debutYear: 2020,
    imageUrl: '/images/groups/title-mitei.svg',
    xFollowers: 68000,
    popularityScore: 90,
    searchVolumeScore: 89,
    description: {
      ja: '「何者かになろうとしなくていい」をテーマに、北海道・札幌から透明感ある叙情的な楽曲を届ける実力派グループ。',
      ko: '「무엇이 되려 하지 않아도 괜찮아」를 테마로 홋카이도 삿포로에서 투명하고 서정적인 음악을 선보이는 감성 실력파 걸그룹.',
      en: 'A critically acclaimed Sapporo-based idol group known for poetic music and emotional live performances.',
    },
    officialSite: 'https://miteititle.com/',
    ticketUrl: 'https://t.livepocket.jp/t/miteititle',
    chekiUrl: 'https://miteititle.stores.jp/',
    scheduleUrl: 'https://miteititle.com/schedule/',
    x: 'https://x.com/MiteiTitle',
    instagram: 'https://www.instagram.com/miteititle/',
    tiktok: 'https://www.tiktok.com/@miteititle',
    youtube: 'https://www.youtube.com/@miteititle',
    subUnits: [],
    members: [
      {
        id: 'mitei-abe-hana',
        groupId: 'title-mitei',
        subUnitId: '',
        name: { ja: { kanji: '阿部葉菜', kana: 'あべ はな' }, ko: { hangul: '아베 하나' }, en: { romaji: 'Hana Abe' } },
        memberColor: '#FFD700',
        memberColorName: { ja: 'イエロー', ko: '옐로우', en: 'Yellow' },
        imageUrl: '/images/members/mitei-abe-hana.svg',
        birthDate: '2000-01-27',
        birthplace: { ja: '北海道', ko: '홋카이도', en: 'Hokkaido' },
        nickname: { ja: 'はなちゃん', ko: '하나짱', en: 'Hana-chan' },
        xFollowers: 42000,
        igFollowers: 58000,
        popularityScore: 90,
        searchVolumeScore: 89,
        isGravureActive: false,
        gravureHighlights: [],
        links: [
          { type: 'x', url: 'https://x.com/hana_mitei', label: { ja: 'X (Twitter)', ko: '공식 X (트위터)', en: 'Official X' }, verified: true, isPrimary: true },
        ],
      },
    ],
  },

  // ==========================================
  // [10] LinQ (후쿠오카)
  // ==========================================
  {
    id: 'linq',
    name: { ja: 'LinQ', ko: '링크 (LinQ)', en: 'LinQ' },
    shortName: { ja: 'リンク', ko: '링크', en: 'LinQ' },
    agency: 'IQ Project (Fukuoka)',
    region: 'fukuoka',
    district: 'tenjin',
    color: '#E60012',
    accentColor: '#FEE2E2',
    debutYear: 2011,
    imageUrl: '/images/groups/linq.svg',
    xFollowers: 95000,
    popularityScore: 88,
    searchVolumeScore: 87,
    description: {
      ja: '「Love in 九州」を掲げ、福岡・天神を拠点に全国・アジアへ笑顔を届ける九州を代表する長寿アイドルグループ。',
      ko: '「Love in 큐슈」를 모토로 후쿠오카 텐진을 거점으로 전국과 아시아로 뻗어나가는 큐슈 대표 아이돌 걸그룹.',
      en: 'Fukuoka\'s premier Kyushu idol group representing Asian regional idol culture.',
    },
    officialSite: 'https://loveinq.com/',
    ticketUrl: 'https://tiget.net/users/5801',
    chekiUrl: 'https://linq.official.ec/',
    scheduleUrl: 'https://loveinq.com/schedule/',
    x: 'https://x.com/LinQ_official',
    instagram: 'https://www.instagram.com/linq_official/',
    tiktok: 'https://www.tiktok.com/@linq_official',
    youtube: 'https://www.youtube.com/@LinQ_official',
    subUnits: [],
    members: [
      {
        id: 'linq-takaki-yuumi',
        groupId: 'linq',
        subUnitId: '',
        name: { ja: { kanji: '高木悠未', kana: 'たかき ゆうみ' }, ko: { hangul: '타카키 유우미' }, en: { romaji: 'Yuumi Takaki' } },
        memberColor: '#E60012',
        memberColorName: { ja: 'パッションレッド', ko: '패션 레드', en: 'Passion Red' },
        imageUrl: '/images/members/linq-takaki-yuumi.svg',
        birthDate: '1997-05-17',
        birthplace: { ja: '福岡県', ko: '후쿠오카현', en: 'Fukuoka' },
        nickname: { ja: 'ゆうみん', ko: '유우민', en: 'Yuumin' },
        xFollowers: 76000,
        igFollowers: 160000,
        popularityScore: 88,
        searchVolumeScore: 87,
        isGravureActive: true,
        gravureHighlights: ['ヤングアニマル グラビア', '福岡TVレギュラー多数'],
        links: [
          { type: 'x', url: 'https://x.com/yuumi_takaki', label: { ja: 'X (Twitter)', ko: '공식 X (트위터)', en: 'Official X' }, verified: true, isPrimary: true },
        ],
      },
    ],
  },

  // ==========================================
  // [11] 手羽先センセーション (나고야)
  // ==========================================
  {
    id: 'tebasen',
    name: { ja: '手羽先センセーション', ko: '테바사키 센세이션 (Tebasaki Sensation)', en: 'Tebasaki Sensation' },
    shortName: { ja: '手羽セン', ko: '테바센', en: 'TebaSen' },
    agency: 'FreeK-Laboratory (Nagoya)',
    region: 'nagoya',
    district: 'sakae',
    color: '#FF8C00',
    accentColor: '#FFF7ED',
    debutYear: 2017,
    imageUrl: '/images/groups/tebasen.svg',
    xFollowers: 52000,
    popularityScore: 87,
    searchVolumeScore: 86,
    description: {
      ja: '「手羽先のように愛されるグループ」を目指し、名古屋・栄を拠点に圧倒的なライブの熱気と王道ポップを届ける名古屋の代表格。',
      ko: '「나고야 명물 테바사키처럼 모두에게 사랑받는 아이돌」을 목표로 나고야 사카에를 거점으로 왕도 팝을 선보이는 나고야 대표 걸그룹.',
      en: 'Nagoya\'s iconic energetic idol sensation bringing melodic pop songs from Sakae, Nagoya.',
    },
    officialSite: 'https://www.tebasen.com/',
    ticketUrl: 'https://t.livepocket.jp/t/tebasen',
    chekiUrl: 'https://tebasen.stores.jp/',
    scheduleUrl: 'https://www.tebasen.com/schedule/',
    x: 'https://x.com/teba_sen',
    instagram: 'https://www.instagram.com/teba_sen/',
    tiktok: 'https://www.tiktok.com/@teba_sen',
    youtube: 'https://www.youtube.com/@tebasen',
    subUnits: [],
    members: [
      {
        id: 'tebasen-hinami-haruka',
        groupId: 'tebasen',
        subUnitId: '',
        name: { ja: { kanji: '日南遥', kana: 'ひなみ はるか' }, ko: { hangul: '히나미 하루카' }, en: { romaji: 'Haruka Hinami' } },
        memberColor: '#FF8C00',
        memberColorName: { ja: 'オレンジ', ko: '오렌지', en: 'Orange' },
        imageUrl: '/images/members/tebasen-hinami-haruka.svg',
        birthDate: '1999-01-24',
        birthplace: { ja: '愛知県', ko: '아이치현', en: 'Aichi' },
        nickname: { ja: 'はるちゃん', ko: '하루짱', en: 'Haru-chan' },
        xFollowers: 38000,
        igFollowers: 52000,
        popularityScore: 87,
        searchVolumeScore: 86,
        isGravureActive: true,
        gravureHighlights: ['ヤングガンガン グラビア'],
        links: [
          { type: 'x', url: 'https://x.com/haruka_tebasen', label: { ja: 'X (Twitter)', ko: '공식 X (트위터)', en: 'Official X' }, verified: true, isPrimary: true },
        ],
      },
    ],
  },
];

// 2. 오시라세 (Notices / Live News Feed)
export const CHIKA_NOTICES_DATA: ChikaNotice[] = [
  {
    id: 'n-fz-tour-2026',
    groupId: 'fruits-zipper',
    groupName: { ja: 'FRUITS ZIPPER', ko: '후르츠 지퍼', en: 'FRUITS ZIPPER' },
    category: 'live',
    date: '2026-08-18',
    badge: { ja: 'ライブ速報', ko: '라이브 속보', en: 'Live News' },
    title: {
      ja: '【全国ツアー2026】さいたまスーパーアリーナ単独2DAYS公演開催決定！チケット一般発売開始',
      ko: '【전국 투어 2026】사이타마 슈퍼 아레나 단독 2DAYS 공연 개최 결정! 일반 예매 오픈',
      en: '[National Tour 2026] Saitama Super Arena 2-Day Solo Live Confirmed! Tickets On Sale',
    },
    summary: {
      ja: '結成4周年を迎えるFRUITS ZIPPER史上最大規模の単独アリーナ公演が決定。チケットはローチケにて受付中。',
      ko: '결성 4주년을 맞이하는 FRUITS ZIPPER 사상 최대 규모의 단독 아레나 공연 개최. 로치케에서 예매 접수 중.',
      en: 'FRUITS ZIPPER announces their largest arena solo live at Saitama Super Arena for their 4th anniversary.',
    },
    url: 'https://fruitszipper.asobisystem.com/news/detail/3394',
  },
  {
    id: 'n-ilife-budokan',
    groupId: 'ilife',
    groupName: { ja: 'iLiFE!', ko: '아이라이프', en: 'iLiFE!' },
    category: 'live',
    date: '2026-08-16',
    badge: { ja: '日本武道館', ko: '일본 무도관', en: 'Budokan' },
    title: {
      ja: 'iLiFE! 日本武道館 単独公演「iLiFE! 5th Anniversary Live」チケット先行受付スタート！',
      ko: 'iLiFE! 일본 무도관 단독 공연 「iLiFE! 5주년 기념 라이브」 티켓 선행 예매 스타트!',
      en: 'iLiFE! Nippon Budokan Solo Live "iLiFE! 5th Anniversary Live" Presale Tickets Open!',
    },
    summary: {
      ja: 'HEROINESのエースグループiLiFE!が悲願の日本武道館ワンマンを達成！TicketDiveにて最速抽選受付中。',
      ko: 'HEROINES의 에이스 iLiFE!의 염원하던 무도관 원맨 라이브 달성! TicketDive에서 최속 추첨 접수 중.',
      en: 'HEROINES flagship group iLiFE! headlines their dream Nippon Budokan solo concert.',
    },
    url: 'https://ticketdive.com/artist/ilife',
  },
  {
    id: 'n-yui-gravure-book',
    groupId: 'fruits-zipper',
    groupName: { ja: 'FRUITS ZIPPER', ko: '후르츠 지퍼', en: 'FRUITS ZIPPER' },
    category: 'gravure',
    date: '2026-08-12',
    badge: { ja: 'グラビア・写真集', ko: '화보・사진집', en: 'Photobook' },
    title: {
      ja: '櫻井優衣（FRUITS ZIPPER）2nd写真集発売決定！週刊プレイボーイにて特別アザーカット公開中',
      ko: '사쿠라이 유이(FRUITS ZIPPER) 2nd 사진집 발매 결정! 주간 플레이보이 특별 아더컷 공개',
      en: 'Yui Sakurai (FRUITS ZIPPER) 2nd Photobook Confirmed with Weekly Playboy Exclusive Cover Cut',
    },
    summary: {
      ja: '1st写真集の大重版に続き、待望の第2弾写真集が決定。各書店・ECにて予約受付開始。',
      ko: '1st 사진집의 대히트에 이어 많은 기대를 모은 2번째 사진집 출간 결정. 각 서점 예약 접수 시작.',
      en: 'Following her bestselling 1st photobook, Yui Sakurai announces her anticipated 2nd volume.',
    },
    url: 'https://fruitszipper.asobisystem.com/',
  },
  {
    id: 'n-appare-single',
    groupId: 'appare',
    groupName: { ja: 'Appare!', ko: '앗파레', en: 'Appare!' },
    category: 'release',
    date: '2026-08-10',
    badge: { ja: '新曲リリース', ko: '신곡 발매', en: 'New Single' },
    title: {
      ja: 'Appare! ニューシングル「サマー・アッパレ・カーニバル」MV解禁＆ストリーミング配信開始！',
      ko: 'Appare! 뉴 싱글 「서머 앗파레 카니발」 MV 공개 및 전 음원 사이트 스트리밍 개시!',
      en: 'Appare! Drops New Summer Anthem "Summer Appare Carnival" Music Video & Global Streaming!',
    },
    summary: {
      ja: '夏フェスを最高潮に盛り上げるAppare!流サマーチューン。YouTubeにてフル尺MV公開中。',
      ko: '여름 페스티벌을 열광의 도가니로 만들 Appare!의 서머 튠. 공식 유튜브 채널에서 MV 감상 가능.',
      en: 'The ultimate festival energy booster is now available across Spotify, Apple Music, and YouTube.',
    },
    url: 'https://appare-official.jp/',
  },
];

// 3. 그라비아 & 비주얼 화보 피처
export const CHIKA_GRAVURE_DATA: GravureFeature[] = [
  {
    id: 'g-sakurai-yui-playboy',
    memberId: 'fz-sakurai-yui',
    memberName: { ja: '櫻井優衣', ko: '사쿠라이 유이', en: 'Yui Sakurai' },
    groupId: 'fruits-zipper',
    groupName: { ja: 'FRUITS ZIPPER', ko: '후르츠 지퍼', en: 'FRUITS ZIPPER' },
    title: { ja: '週刊プレイボーイ 表紙巻頭グラビア', ko: '주간 플레이보이 표지 & 권두 그라비아', en: 'Weekly Playboy Cover Feature' },
    magazine: '週刊プレイボーイ (Weekly Playboy)',
    releaseDate: '2026-08',
    imageUrl: '/images/members/fz-sakurai-yui.svg',
    url: 'https://www.grajapa.shueisha.co.jp/',
  },
  {
    id: 'g-shinzome-riri-youngjump',
    memberId: 'ilife-shinzome-riri',
    memberName: { ja: '心花りり', ko: '신조메 리리', en: 'Riri Shinzome' },
    groupId: 'ilife',
    groupName: { ja: 'iLiFE!', ko: '아이라이프', en: 'iLiFE!' },
    title: { ja: '週刊ヤングジャンプ 表紙＆巻頭グラビア', ko: '주간 영점프 표지 & 권두 화보', en: 'Weekly Young Jump Cover Gravure' },
    magazine: '週刊ヤングジャンプ (Young Jump)',
    releaseDate: '2026-07',
    imageUrl: '/images/members/ilife-shinzome-riri.svg',
    url: 'https://youngjump.jp/',
  },
  {
    id: 'g-matsumoto-karen-larme',
    memberId: 'fz-matsumoto-karen',
    memberName: { ja: '松本かれん', ko: '마츠모토 카렌', en: 'Karen Matsumoto' },
    groupId: 'fruits-zipper',
    groupName: { ja: 'FRUITS ZIPPER', ko: '후르츠 지퍼', en: 'FRUITS ZIPPER' },
    title: { ja: 'LARME 特集ビジュアルグラビア', ko: 'LARME 패션 & 뷰티 비주얼 화보', en: 'LARME Visual & Fashion Feature' },
    magazine: 'LARME',
    releaseDate: '2026-06',
    imageUrl: '/images/members/fz-matsumoto-karen.svg',
    url: 'https://larme.co/',
  },
  {
    id: 'g-tsurumi-moe-animal',
    memberId: '2z-tsurumi-moe',
    memberName: { ja: '鶴見萌', ko: '츠루미 모에', en: 'Moe Tsurumi' },
    groupId: '2zicon',
    groupName: { ja: '虹のコンキスタドール', ko: '니지의 콘키스타도르', en: '2zicon' },
    title: { ja: 'ヤングアニマル 表紙巻頭サマーグラビア', ko: '영 애니멀 표지 & 서머 비키니 화보', en: 'Young Animal Summer Cover' },
    magazine: 'ヤングアニマル (Young Animal)',
    releaseDate: '2026-07',
    imageUrl: '/images/members/2z-tsurumi-moe.svg',
    url: 'https://www.younganimal.com/',
  },
  {
    id: 'g-aoba-hinata-champ',
    memberId: 'ft-aoba-hinata',
    memberName: { ja: '青葉ひなり', ko: '아오바 히나리', en: 'Hinari Aoba' },
    groupId: 'festive',
    groupName: { ja: 'FES☆TIVE', ko: '페스티브', en: 'FES☆TIVE' },
    title: { ja: 'ヤングチャンピオン 表紙巻頭グラビア', ko: '영 챔피언 표지 & 권두 화보', en: 'Young Champion Cover Gravure' },
    magazine: 'ヤングチャンピオン (Young Champion)',
    releaseDate: '2026-05',
    imageUrl: '/images/members/ft-aoba-hinata.svg',
    url: 'https://www.akitashoten.co.jp/',
  },
];

function seed() {
  const dataDir = path.join(__dirname, '..', 'data');
  if (!fs.existsSync(dataDir)) fs.mkdirSync(dataDir, { recursive: true });

  fs.writeFileSync(path.join(dataDir, 'chika-groups.json'), JSON.stringify(CHIKA_GROUPS_COMPLETE, null, 2), 'utf-8');
  fs.writeFileSync(path.join(dataDir, 'chika-notices.json'), JSON.stringify(CHIKA_NOTICES_DATA, null, 2), 'utf-8');
  fs.writeFileSync(path.join(dataDir, 'chika-gravure.json'), JSON.stringify(CHIKA_GRAVURE_DATA, null, 2), 'utf-8');

  console.log(`✅ Seeded Groups (${CHIKA_GROUPS_COMPLETE.length}), Notices (${CHIKA_NOTICES_DATA.length}), Gravure (${CHIKA_GRAVURE_DATA.length})!`);
}

seed();
